=== FromentLorenzo/XMHelloFresh/XMHelloFresh.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="Scenario7.xsl"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Recettes -->
    <xs:element name="Recettes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Recette" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Recette-->
    <xs:element name="Recette">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nom" type="xs:string"/>
                <xs:element name="Nombre_de_personnes" type="xs:integer"/>
                <xs:element name="Ingredients">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ingredient" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="idIngredient" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="EtapesDeRecette">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Etape" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Image" type="xs:anyURI"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Ingrédients-->
    <xs:element name="Ingredients">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Ingredient" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Ingrédient-->
    <xs:element name="Ingredient">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nom" type="xs:string"/>
                <xs:element name="Quantité" type="xs:integer"/>
                <xs:element name="Unité" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- Menus -->
    <xs:element name="Menus">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Menu" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Menu -->
    <xs:element name="Menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nom" type="xs:string"/>
                <xs:element name="Prix" type="xs:integer"/>
                <xs:element ref="Recettes_Du_Menu"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- Recettes_Du_Menu -->
    <xs:element name="Recettes_Du_Menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Recette_Du_Menu" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Recette_Du_Menu -->
    <xs:element name="Recette_Du_Menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nom" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="idRecette" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- Commandes -->
    <xs:element name="Commandes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Commande" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Commande -->
    <xs:element name="Commande">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Utilisateur">
                    <xs:complexType>
                        <xs:attribute name="idUtilisateur" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Date" type="xs:string"/>
                <xs:element name="Heure" type="xs:string"/>
                <xs:element name="Adresse" type="xs:string"/>
                <xs:element name="Numéro_de_téléphone" type="xs:string"/>
                <xs:element name="Livreur">
                    <xs:complexType>
                        <xs:attribute name="idLivreur" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Statut" type="xs:string"/>
                <xs:element name="Prix" type="xs:integer"/>
                <xs:element name="Menu">
                    <xs:complexType>
                        <xs:attribute name="idMenu" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- Commentaires -->
    <xs:element name="Commentaires">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Commentaire" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Commentaire">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Utilisateur">
                    <xs:complexType>
                        <xs:attribute name="idUtilisateur" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Note">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-5]"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Commande">
                    <xs:complexType>
                        <xs:attribute name="idCommande" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Texte" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    

    <!-- Utilisateurs -->
    <xs:element name="Utilisateurs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Utilisateur" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Utilisateur -->
    <xs:element name="Utilisateur">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nom" type="xs:string"/>
                <xs:element name="Prénom" type="xs:string"/>
                <xs:element name="Adresse" type="xs:string"/>
                <xs:element name="Numéro_de_téléphone" type="xs:string"/>
                <xs:element name="Adresse_mail" type="xs:string"/>
                <xs:element name="Mot_de_passe_hashé" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>


    <!-- Livreurs -->
    <xs:element name="Livreurs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Livreur" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Livreur -->
    <xs:element name="Livreur">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nom" type="xs:string"/>
                <xs:element name="Prénom" type="xs:string"/>
                <xs:element name="Numéro_de_téléphone" type="xs:string"/>
                <xs:element name="Moyen_de_transport"></xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    


    <!-- Main Element -->
    <xs:element name="XMHelloFresh">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Recettes"/>
                <xs:element ref="Menus"/>
                <xs:element ref="Ingredients"/>
                <xs:element ref="Commandes"/>
                <xs:element ref="Commentaires"/>
                <xs:element ref="Utilisateurs"/>
                <xs:element ref="Livreurs"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== FromentLorenzo/XMHelloFresh/XMHelloFresh.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMHelloFresh xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMHelloFresh.xsd">
               
    <Recettes>
        <Recette id="1">
            <Nom> Mousse au chocolat </Nom>
            <Nombre_de_personnes> 6 </Nombre_de_personnes>
            <Ingredients>
                <Ingredient idIngredient="1"/>
                <Ingredient idIngredient="2"/>
                <Ingredient idIngredient="3"/>
            </Ingredients>
            <Image>https://img.cuisineaz.com/1280x720/2017/05/09/i125843-mousse-au-chocolat-au-lait.jpeg</Image>
        </Recette>
    </Recettes>
    <Menus>
        <Menu id="1">
            <Nom>Repas de Saint-Valentin</Nom>
            <Prix>60</Prix>
            <Recettes_Du_Menu>
                <Recette_Du_Menu idRecette="1">
                    <Nom>Mousse au chocolat</Nom>
                </Recette_Du_Menu>
            </Recettes_Du_Menu>
        </Menu>
    </Menus>
    <Ingredients>
        <Ingredient id="1">
            <Nom>Chocolat noir</Nom>
            <Quantité>200</Quantité>
            <Unité>g</Unité>
        </Ingredient>
        <Ingredient id="2">
            <Nom>Oeuf</Nom>
            <Quantité>6</Quantité>
            <Unité></Unité>
        </Ingredient>
        <Ingredient id="3">
            <Nom>Sucre</Nom>
            <Quantité>100</Quantité>
            <Unité>g</Unité>
        </Ingredient>
    </Ingredients>
    <Commandes>
        <Commande id="1">
            <Utilisateur idUtilisateur="1"/>
            <Date>01/03/2024</Date>
            <Heure>11:20</Heure>
            <Adresse>2 Allée des Perdrix Antibes</Adresse>
            <Numéro_de_téléphone> 0652526012 </Numéro_de_téléphone>
            <Livreur idLivreur="1"/>
            <Statut>En Cours de Livraison</Statut>
            <Prix>60</Prix>
            <Menu idMenu="1"/>
        </Commande>
    </Commandes>
    <Commentaires>
        <Commentaire>
            <Utilisateur idUtilisateur="1"/>
            <Note>4/5</Note>
            <Commande idCommande="1"/>
            <Texte> Nous nous sommes régalé avec ma femme. La mousse était un peu salé</Texte>
        </Commentaire>
    </Commentaires>
    <Utilisateurs>
        <Utilisateur id="1">
            <Nom>Froment</Nom>
            <Prénom>Lorenzo</Prénom>
            <Adresse>Allée des Perdrix, Antibes</Adresse>
            <Numéro_de_téléphone> 0652526012 </Numéro_de_téléphone>
            <Adresse_mail> lorenzo.froment@gmail.com </Adresse_mail>
            <Mot_de_passe_hashé> JdzZh23h3hife4iZ </Mot_de_passe_hashé>
        </Utilisateur>
    </Utilisateurs>
    <Livreurs>
      <Livreur id="1">
        <Nom> Delias </Nom>
        <Prénom> Théo </Prénom>
        <Numéro_de_téléphone> 0609234822 </Numéro_de_téléphone>
        <Moyen_de_transport> Trotinette</Moyen_de_transport>
      </Livreur>  
    </Livreurs>
</XMHelloFresh>
